### ISSUE TITLE
[FEATURE REQUEST] Support multiple images

### ISSUE THREAD

**Issue by GreenMan36** [Twxtter/Twxtter-main#9] opened 2022-05-24 10:09 UTC
**Is your feature request related to a problem? Please describe.**
When sending a Twitter link it will show all images attached to that tweet, however twxtter links only shows the first image.

**Describe the solution you'd like**
For this 
![image](https://user-images.githubusercontent.com/5887406/170007133-7719bdef-416f-4e12-9ae2-c6b37f47be8d.png)
To show more images like this
![image](https://user-images.githubusercontent.com/5887406/170006957-e0057329-8d06-4834-8a59-428dede62c34.png)

**Describe alternatives you've considered**
Using the normal Twitter embed that looks slightly different.
This is a minor thing but it would allow me to just default replace all twitter links with twxtter using an addon/script on the web or Discord plugin on pc/mobile.

**Comment by GreenMan36** [comment] 2022-05-24 10:11
In this screenshot from a competing fork; it at least shows you that there's multiple images in the embed in the top most part.
![image](https://user-images.githubusercontent.com/5887406/170007913-cb5cb14a-40a0-41ed-b180-e780370286ec.png)

**Comment by lyricalpaws** [comment] 2022-05-26 17:56
I'm more than happy to add the `Image - x/x` tag, though I won't be adding the image merging feature that vx added, this is due to server costs, and the fact that it is a massive resource drain.

**Comment by lyricalpaws** [comment] 2022-05-26 23:03
Added in #22 
![image](https://user-images.githubusercontent.com/26838744/170593312-de077fa7-6831-43a7-828b-a16e9aa5d5d9.png)

**Comment by lyricalpaws** [comment] 2022-05-26 23:04
Also regarding the twitter multi image, it is currently impossible due to Twitter having special embed privlidge (as confirmed by Discord devs)

**Closed as completed by lyricalpaws** 2022-05-26 23:04 UTC
Labels: enhancement
